########################################################
## GLOBAL CONFIG
########################################################

# Set the prefix
prefix-message: "<bold><gold>SERVER</gold> <dark_gray>>></dark_gray></bold>"

non-player-message: "<red>You need to be a player to execute this command.</red>"

invalid-player-message: "<gradient:#FF0000:#FF3DC5>Invalid player!</gradient>"

no-permission-message: "<gradient:#FF0000:#FF3DC5>You don't have the \"<permission>\" permission to use this command!</gradient>"

########################################################
##            WILD COMMAND CONFIG /WILD              ###
########################################################

# True if you want to limit how far it teleports players
world-border: false
# How many blocks away they CAN spawn(not will)
# If no world border, limit is automatically 25,000 blocks
border: 200

# Wild cool-down time
cool-down-time: 10

# Message displayed when player still in cool off period
cool-down-message: "&7>> &fYou can use this &b/wild &fin &c{seconds-left} &fseconds"

# Message displayed when a player is in the nether or end world
incorrect-world-message: "&7>> &fYou cannot use &b/wild &fin this world"

# Message displayed when a player is teleported
random-location: "&7>> &fYou have been teleported to a random location"

########################################################
## GOD COMMAND
########################################################

god-enabled-message: "<gradient:#00FFEC:#FF00FB>Your god mode has been enabled!</gradient>"
god-disabled-message: "<gradient:#00FFEC:#FF00FB>Your god mode has been disabled!</gradient>"

god-enabled-other-message: "<gradient:#00FFEC:#FF00FB>You enabled god mode for <player>!</gradient>"
god-disabled-other-message: "<gradient:#00FFEC:#FF00FB>You disabled god mode for <player>!</gradient>"

########################################################
## GUI COMMAND
########################################################

test-message: "<gradient:#00FFEC:#FF00FB>Testing click events.</gradient>"