name: XOSurvivalCore
version: '${project.version}'
main: fwoostybots.com.xosurvivalcore.Main
api-version: 1.18
authors: [ Someone, FroostySnoowman ]
description: XOSurvival Core Plugin
depend: [Vault]
commands:
  god:
    description: Become invunerable
    usage: /<command>
  warp:
    description: Open a gui
    usage: /<command>
  wild:
    description: Go to the wilderness
    usage: /<command>
  wildgui:
    description: GUI stuff
    usage: /<command>