name: XOSurvivalCore
version: '${project.version}'
main: fwoostybots.com.xosurvivalcore.Main
api-version: 1.18
authors: [ Someone, FroostySnoowman ]
description: XOSurvival Core Plugin
depend: [Vault]